### ISSUE TITLE
Detection  from Windows defender

### ISSUE THREAD

**Issue by Alessandro-Me** [optiv/Mangle#5] opened 2022-06-30 04:15 UTC
Hi, i tested chisel with your tool and i didn't get any luck got detected by defender when i dropped on the disk. Do you have any suggestion?

**Comment by andreluna** [comment] 2022-06-30 11:54
What command do you used?

**Comment by Alessandro-Me** [comment] 2022-06-30 12:37
This command "Mangle-main>Mangle.exe -I chisel.exe -M -O test.exe -S 100" - Maybe it is wrong

**Comment by Tylous** [comment] 2022-06-30 14:41
So, do I have this correct when you are making your test.exe file on a Windows machine, defender is enabled?

**Comment by Alessandro-Me** [comment] 2022-07-01 00:19
Hi Tylous, I created the test.exe from a Windows machine with defender disabled - when i copy and paste the test.exe file into a Windows machine with defender enabled gets detected

**Comment by Tylous** [comment] 2022-07-01 16:21
So you don't need to do the -M atm as that only works with golang (I am working on the C#, C and rust strings right now) but the size might need to be bigger (play around with it), and try using the -C to clone the cert from a valid windows process like cmd.exe or Word.exe.

**Comment by Alessandro-Me** [comment] 2022-07-01 16:55
Hey Tylous, but chiesel is written in Go (golang) so the -M should work,
please correct me if I'm wrong

**Comment by Tylous** [comment] 2022-07-05 16:10
My bad I wasn't aware it was a golang tool. Did my other suggestions work?

**Comment by Alessandro-Me** [comment] 2022-07-06 12:56
unfortunately, didn't work. Any idea why the strings option -M doesn't help?

**Comment by Tylous** [comment] 2022-07-06 16:43
Are you using the pre-compiled ones or compiling it yourself from the source (if you are what is your build command)?

**Comment by Alessandro-Me** [comment] 2022-07-07 02:05
i tested both the pre-compiled ones and the source code - if you can give a test and see if works for you

**Comment by Tylous** [comment] 2022-07-07 15:18
So after doing some the issue appears to be there are numerous strings at the beginning of the file that are IoC's specific to chisel. As such Mangle would not know them and would not have rules to replace them. You can see this because the standard windows defender that comes with all systems is able to call out the file as the tool chisel. 
![image](https://user-images.githubusercontent.com/15052743/177809277-e01fc612-5cb8-4282-8d2b-5589cd6cb262.png)

A simple grep of strings shows tons of references to chisel which would make it easier to spot. I suspect the issue is because everyone tests on the free windows defender with sample submission on there are some easy-to-catch strings.

![image](https://user-images.githubusercontent.com/15052743/177809651-5ddbef0e-fa2b-4028-95bc-bdf7b47256e0.png)

 I confirmed this by testing the same file against Microsoft's Paid for Kernel EDR MDE and the file landed on disk with no problem. 

![image](https://user-images.githubusercontent.com/15052743/177809810-7bde6f43-6379-426e-9d53-6e1645e05c25.png)

Based on all this either you need to go back to the author or do some code-level customization yourself as this is very much a cat and mouse situation.

**Comment by Alessandro-Me** [comment] 2022-07-08 14:06
Thank you so much your test is very useful - I’ll start to work on the
code-level customisation also I’ll give a test with CS and see if it detect
it or no - I’ll let you know

**Closed as completed** 2022-07-14 16:36 UTC
